//! Emission of Lean 4 certificates.
//!
//! The contract for everything in this module: the emitted text must be checkable
//! with no trust in this program. It imports only `Certs.Basic`, which in turn
//! imports only Lean core — no Mathlib, no external solver, no oracle. A reader
//! runs `lake build` and gets a yes or a no.
//!
//! This is the whole point of the project. A search program reporting its own
//! results is an unverified claim; the same result as a theorem the kernel
//! accepts is not.

use crate::problems::{CapSet, CoveringDesign};

fn lean_nat_list(xs: &[u8]) -> String {
    let body: Vec<String> = xs.iter().map(|x| x.to_string()).collect();
    format!("[{}]", body.join(", "))
}

fn lean_list_of_lists(rows: &[Vec<u8>], indent: &str) -> String {
    let body: Vec<String> = rows
        .iter()
        .map(|r| format!("{}  {}", indent, lean_nat_list(r)))
        .collect();
    format!("[\n{}\n{}]", body.join(",\n"), indent)
}

/// A cap set certificate: the points, that the set is a cap, and its size.
pub fn capset_lean(problem: &CapSet, points: &[u16]) -> String {
    let n = problem.n;
    let size = points.len();
    let ident = format!("capset{}_{}", n, size);
    let rows: Vec<Vec<u8>> = points.iter().map(|&p| problem.digits(p)).collect();

    format!(
        r#"import Certs.Basic

/-!
# Cap set in `F_3^{n}` of size {size}

A cap set contains no three distinct collinear points. Over `F_3` the third point
on the line through `a` and `b` is determined, so the property is a finite check.

Coordinates are listed least-significant first. Generated by the `ramanujan`
harness; the theorems below are what make it a result rather than an assertion.
-/

namespace Certs

def {ident} : List (List Nat) :=
  {points}

theorem {ident}_isCap : capOK {n} {ident} = true := by decide

theorem {ident}_card : {ident}.length = {size} := by rfl

end Certs
"#,
        n = n,
        size = size,
        ident = ident,
        points = lean_list_of_lists(&rows, "  ")
    )
}

/// A covering design certificate: the blocks, and that they cover every `t`-subset.
pub fn covering_lean(problem: &CoveringDesign, blocks: &[u64]) -> String {
    let (v, k, t) = (problem.v, problem.k, problem.t);
    let b = blocks.len();
    let ident = format!("covering_{}_{}_{}_b{}", v, k, t, b);
    let rows: Vec<Vec<u8>> = blocks
        .iter()
        .map(|&m| (0..v).filter(|&e| m & (1 << e) != 0).map(|e| e as u8).collect())
        .collect();

    format!(
        r#"import Certs.Basic

/-!
# Covering design `C({v}, {k}, {t})` with {b} blocks

Every {t}-subset of `{{0, …, {vm1}}}` lies inside at least one listed block, so the
covering number `C({v}, {k}, {t})` is at most {b}.

Generated by the `ramanujan` harness.
-/

namespace Certs

def {ident} : List (List Nat) :=
  {blocks}

theorem {ident}_covers : coveringOK {v} {k} {t} {ident} = true := by decide

theorem {ident}_blocks : {ident}.length = {b} := by rfl

end Certs
"#,
        v = v,
        k = k,
        t = t,
        b = b,
        vm1 = v.saturating_sub(1),
        ident = ident,
        blocks = lean_list_of_lists(&rows, "  ")
    )
}
